const templateGroups = {
  Receipts: [
    "Cash Receipt",
    "Donation Receipt",
    "General Receipt",
    "Pay Stub Paystub",
    "Payment Receipt",
    "Receipt Book",
    "Rent Receipt",
    "Sales Receipt",
  ],
  Estimates: [
    "Construction Estimate Template",
    "Contractor Estimate Template",
    "Estimate Template",
    "Job Estimate Template",
    "Painting Estimate Template",
    "Roofing Estimate Template",
  ],
  "Business Agreements": [
    "Consulting Agreement Template",
    "Independent Contractor Agreement",
    "Loan Agreement Template",
    "Non-Disclosure Agreement Template",
    "Operating Agreement Template",
    "Partnership Agreement Template",
    "Promissory Note Template",
    "Purchase Agreement Template",
    "Service Agreement Template",
    "Settlement Agreement Template",
    "Subcontractor Agreement Template",
  ],
  "Financial Statements": [
    "Balance Sheet",
    "Profit & Loss (P&L) Statement",
  ],
  "Business Letters": [
    "Business Letter Template",
    "Cease and Desist Letter Template",
    "Demand Letter Template",
    "Offer Letter Template",
    "Termination Letter Template",
  ],
  Contracts: [
    "Business Contract",
    "Catering Contract",
    "Cleaning Contract",
    "Construction Contract",
    "Consulting Contract",
    "Contractor Contract",
    "Employment Contract",
    "Freelance Contract",
    "General Contract",
    "Landscaping Contract",
    "Nanny Contract",
    "Photography Contract",
    "Real Estate Contract",
    "Roofing Contract",
    "SEO Contract",
    "Sales Contract",
    "Service Contract",
  ],
  "Bill of Sale": [
    "Bill of Sale Template",
    "Boat Bill of Sale Template",
    "Car Bill of Sale Template",
    "Gun Bill of Sale Template",
    "Motorcycle Bill of Sale Template",
    "RV Bill of Sale Template",
    "Trailer Bill of Sale Template",
  ],
};

export const categories = ["All templates", ...Object.keys(templateGroups)];
export const serviceCategories = ["All", "Popular", "Tax", "Immigration", "Passport & travel", "Healthcare"];

const templateDescriptions = {
  "Cash Receipt": "Confirm a cash payment with amount and payer details.",
  "Donation Receipt": "Confirm a donation for donor and tax records.",
  "General Receipt": "Record any payment with payer, amount, and date details.",
  "Pay Stub Paystub": "Summarize employee earnings, deductions, and net pay.",
  "Payment Receipt": "Confirm a completed payment with transaction details.",
  "Receipt Book": "Keep organized records of recurring payments.",
  "Rent Receipt": "Confirm rent payments for landlords and tenants.",
  "Sales Receipt": "Record items sold, prices, taxes, and total paid.",
  "Construction Estimate Template": "Estimate construction labor, materials, and project costs.",
  "Contractor Estimate Template": "Quote contractor labor, materials, and project costs.",
  "Estimate Template": "Share projected costs before work or services begin.",
  "Job Estimate Template": "Break down job tasks, materials, labor, and pricing.",
  "Painting Estimate Template": "Estimate paint, supplies, labor, and project pricing.",
  "Roofing Estimate Template": "Estimate roofing materials, labor, and total costs.",
  "Consulting Agreement Template": "Set consulting scope, fees, and deliverables.",
  "Independent Contractor Agreement": "Define independent work, payment, and ownership.",
  "Loan Agreement Template": "Record loan amount, interest, and repayment terms.",
  "Non-Disclosure Agreement Template": "Protect confidential information shared between parties.",
  "Operating Agreement Template": "Set ownership and operating rules for an LLC.",
  "Partnership Agreement Template": "Define partner roles, ownership, and profit sharing.",
  "Promissory Note Template": "Promise repayment with amount, dates, and interest.",
  "Purchase Agreement Template": "Document a purchase, price, terms, and delivery.",
  "Service Agreement Template": "Define services, fees, deadlines, and responsibilities.",
  "Settlement Agreement Template": "Resolve a dispute with agreed payment and terms.",
  "Subcontractor Agreement Template": "Set subcontracted work, payment, and deadlines.",
  "Balance Sheet": "Summarize assets, liabilities, and equity.",
  "Profit & Loss (P&L) Statement": "Track revenue, expenses, and profit over time.",
  "Business Letter Template": "Write a clear formal message for business needs.",
  "Cease and Desist Letter Template": "Demand that harmful or unauthorized activity stop.",
  "Demand Letter Template": "Request payment or action by a clear deadline.",
  "Offer Letter Template": "Present a job offer, compensation, and terms.",
  "Termination Letter Template": "Confirm employment ending, date, and next steps.",
  "Business Contract": "Set terms for a commercial relationship or deal.",
  "Catering Contract": "Define menu, event services, fees, and cancellation.",
  "Cleaning Contract": "Outline cleaning scope, schedule, and payment.",
  "Construction Contract": "Set project scope, costs, timeline, and duties.",
  "Consulting Contract": "Agree on consulting work, fees, and deliverables.",
  "Contractor Contract": "Define contractor work, payment, and obligations.",
  "Employment Contract": "Set role, compensation, benefits, and conditions.",
  "Freelance Contract": "Define freelance scope, deadlines, fees, and rights.",
  "General Contract": "Record the core terms agreed between two parties.",
  "Landscaping Contract": "Define services, schedule, and pricing for landscaping.",
  "Nanny Contract": "Define childcare duties, schedule, pay, and policies.",
  "Photography Contract": "Set shoot details, fees, delivery, and image rights.",
  "Real Estate Contract": "Record property transaction terms and deadlines.",
  "Roofing Contract": "Set roofing scope, materials, price, and warranty.",
  "SEO Contract": "Define SEO services, goals, reporting, and fees.",
  "Sales Contract": "Set product sale terms, payment, and delivery.",
  "Service Contract": "Detail services, responsibilities, fees, and timing.",
  "Bill of Sale Template": "A general bill of sale for any item.",
  "Boat Bill of Sale Template": "Transfer boat ownership with sale details.",
  "Car Bill of Sale Template": "Document a vehicle sale with all details.",
  "Gun Bill of Sale Template": "Document a firearm transfer between parties.",
  "Motorcycle Bill of Sale Template": "Document a motorcycle sale between parties.",
  "RV Bill of Sale Template": "Transfer RV ownership with documented terms.",
  "Trailer Bill of Sale Template": "Record the sale of a trailer.",
};

export const templates = Object.entries(templateGroups).flatMap(([category, titles]) =>
  titles.map((title) => ({
    id: `${category}:${title}`,
    category,
    title,
    description: templateDescriptions[title],
    preview: `template-previews/${category}-${title}.png`,
  })),
);

export const formTemplates = [
  {
    id: "forms:form-w-9",
    category: "Tax",
    title: "Form W-9",
    description: "Request for Taxpayer Identification Number.",
    preview: "form-previews/form-w9.png",
  },
  {
    id: "forms:form-w-4",
    category: "Tax",
    title: "Form W-4",
    description: "Employee's Withholding Certificate.",
    preview: "form-previews/form-w4.png",
  },
  {
    id: "forms:form-1099-nec",
    category: "Tax",
    title: "Form 1099-NEC",
    description: "Nonemployee Compensation.",
    preview: "form-previews/form-1099-nec.png",
    previewTone: "monochrome",
  },
  {
    id: "forms:form-w-2",
    category: "Tax",
    title: "Form W-2",
    description: "Wage and Tax Statement.",
    preview: "form-previews/form-w2.png",
    previewTone: "monochrome",
  },
  {
    id: "forms:form-1040-es",
    category: "Tax",
    title: "Form 1040-ES",
    description: "Estimated Tax for Individuals.",
    preview: "form-previews/form-1040-es.png",
  },
  {
    id: "forms:form-941",
    category: "Tax",
    title: "Form 941",
    description: "Employer's Quarterly Federal Tax Return.",
    preview: "form-previews/form-941.png",
  },
  {
    id: "forms:schedule-c",
    category: "Tax",
    title: "Schedule C (Form 1040)",
    description: "Profit or Loss From Business.",
    preview: "form-previews/schedule-c.png",
  },
  {
    id: "forms:form-i-9",
    category: "Immigration",
    title: "Form I-9",
    description: "Employment Eligibility Verification.",
    preview: "form-previews/form-i9.png",
  },
  {
    id: "forms:form-i-864",
    category: "Immigration",
    title: "Form I-864",
    description: "Affidavit of Support.",
    preview: "form-previews/form-i864.png",
  },
  {
    id: "forms:form-ds-11",
    category: "Passport & travel",
    title: "Form DS-11",
    description: "Application for a U.S. Passport.",
    preview: "form-previews/form-ds11.png",
  },
  {
    id: "forms:form-ds-82",
    category: "Passport & travel",
    title: "Form DS-82",
    description: "U.S. Passport Renewal.",
    preview: "form-previews/form-ds82.png",
  },
  {
    id: "forms:form-cms-1500",
    category: "Healthcare",
    title: "Form CMS-1500",
    description: "Health Insurance Claim Form.",
    preview: "form-previews/form-cms1500.png",
    previewTone: "monochrome",
  },
];

export const invoiceTemplates = [
  {
    id: "invoice:simple-invoice",
    category: "Popular",
    title: "Simple Invoice",
    description: "A clean invoice for billing any client.",
    preview: "invoice-previews/simple-invoice.png",
  },
  {
    id: "invoice:commercial-invoice",
    category: "Popular",
    title: "Commercial Invoice",
    description: "Itemize goods for shipments and customs.",
    preview: "invoice-previews/commercial-invoice.png",
  },
  {
    id: "invoice:freelance-invoice",
    category: "Popular",
    title: "Freelance Invoice",
    description: "Bill clients for project or hourly work.",
    preview: "invoice-previews/freelance-invoice.png",
  },
  {
    id: "invoice:contractor-invoice",
    category: "Popular",
    title: "Contractor Invoice",
    description: "Charge for labor, materials, and milestones.",
    preview: "invoice-previews/contractor-invoice.png",
  },
  {
    id: "invoice:consulting-invoice",
    category: "Popular",
    title: "Consulting Invoice",
    description: "Bill for advisory hours and retainers.",
    preview: "invoice-previews/consulting-invoice.png",
  },
  {
    id: "invoice:construction-invoice",
    category: "Popular",
    title: "Construction Invoice",
    description: "Itemize labor, materials, and equipment.",
    preview: "invoice-previews/construction-invoice.png",
  },
  {
    id: "invoice:proforma-invoice",
    category: "Popular",
    title: "Proforma Invoice",
    description: "Send a preliminary estimate before delivery.",
    preview: "invoice-previews/proforma-invoice.png",
  },
  {
    id: "invoice:square-invoice",
    category: "Popular",
    title: "Square Invoice",
    description: "Use a modern format for fast payment.",
    preview: "invoice-previews/square-invoice.png",
  },
  {
    id: "invoice:auto-repair-invoice",
    category: "Popular",
    title: "Auto Repair Invoice",
    description: "List parts, labor, and vehicle repair fees.",
    preview: "invoice-previews/auto-repair-invoice.png",
  },
  {
    id: "invoice:cleaning-invoice",
    category: "Popular",
    title: "Cleaning Invoice",
    description: "Bill cleaning services by visit or hour.",
    preview: "invoice-previews/cleaning-invoice.png",
  },
  {
    id: "invoice:plumbing-invoice",
    category: "Popular",
    title: "Plumbing Invoice",
    description: "Charge for parts, labor, and call-out fees.",
    preview: "invoice-previews/plumbing-invoice.png",
  },
  {
    id: "invoice:catering-invoice",
    category: "Popular",
    title: "Catering Invoice",
    description: "Itemize menu, guests, and event service.",
    preview: "invoice-previews/catering-invoice.png",
  },
];

export const templatesPerPage = 12;
